### ISSUE TITLE
Prepare the first release for bos

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-bos#9]
bos has passed the integration tests now, we need to prepare the first release of bos.

## Roadmap

- [ ] Add docs in go-storage README and site
- [ ] Bump new versions
- [ ] Add bos in go-storage-example
- [ ] Share it inside our forum to the community!

**Comment by Xuanwo** [comment]
ping @abyss-w for help.

**Comment by abyss-w** [comment]
> ping @abyss-w for help.

Got it!

**Comment by abyss-w** [comment]
ping @Xuanwo: Could you please add a tag for bos and release the version？

**Comment by Xuanwo** [comment]
Let's leave this honer to @JinnyYi !

**Comment by JinnyYi** [comment]
> Let's leave this honer to @JinnyYi !

ref: https://github.com/beyondstorage/go-service-bos/releases/tag/v1.0.0

**Comment by abyss-w** [comment]
Done!
